# Generated by Django 5.0.14 on 2026-02-08 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.IntegerField(default=2500, help_text='Target daily calorie intake')),
                ('daily_water_ml', models.IntegerField(default=2500, help_text='Target daily water in ml')),
                ('daily_sleep_hours', models.DecimalField(decimal_places=1, default=8.0, help_text='Target hours of sleep', max_digits=4)),
                ('daily_exercise_minutes', models.IntegerField(default=45, help_text='Target active minutes per day')),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Target weight in kg', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
