# Generated by Django 5.0.14 on 2026-02-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (Office Job)'), ('lightly_active', 'Lightly Active (1-3 days/week)'), ('moderately_active', 'Moderately Active (3-5 days/week)'), ('very_active', 'Very Active (6-7 days/week)')], default='moderately_active', max_length=20),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='primary_goal',
            field=models.CharField(choices=[('lose_weight', 'Lose Weight'), ('maintain', 'Maintain Weight'), ('gain_muscle', 'Gain Muscle')], default='maintain', max_length=20),
        ),
    ]
