# Generated by Django 5.0.14 on 2026-02-08 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories_per_hour', models.IntegerField(help_text='Burn rate per hour (kcal)')),
                ('intensity_default', models.CharField(default='Medium', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='activity_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='calories_burned',
            field=models.IntegerField(help_text='Calculated calories burned'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='intensity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='exercise_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercise.exercisetype'),
        ),
    ]
